import { and, desc, eq, gte, lte } from "drizzle-orm";
import { ClipboardList } from "lucide-react";
import { requirePermission } from "@/lib/auth/authorization";
import { getDb } from "@/lib/db";
import { auditLogs, users } from "@/lib/db/schema";

function startOfDay(value?: string) { return value && /^\d{4}-\d{2}-\d{2}$/.test(value) ? new Date(`${value}T00:00:00`) : undefined; }
function endOfDay(value?: string) { return value && /^\d{4}-\d{2}-\d{2}$/.test(value) ? new Date(`${value}T23:59:59.999`) : undefined; }

export default async function AuditPage({ searchParams }: { searchParams: Promise<{ inicio?: string; fim?: string }> }) {
  await requirePermission("auditoria.visualizar"); const { inicio = "", fim = "" } = await searchParams; const filters = [];
  const from = startOfDay(inicio); const to = endOfDay(fim); if (from) filters.push(gte(auditLogs.createdAt, from)); if (to) filters.push(lte(auditLogs.createdAt, to));
  const rows = await getDb().select({ id: auditLogs.id, action: auditLogs.action, entityType: auditLogs.entityType, createdAt: auditLogs.createdAt, actor: users.name, ipAddress: auditLogs.ipAddress }).from(auditLogs).leftJoin(users, eq(auditLogs.actorId, users.id)).where(filters.length ? and(...filters) : undefined).orderBy(desc(auditLogs.createdAt)).limit(300);
  return <main className="mx-auto max-w-6xl p-4 sm:p-7 lg:p-9"><header className="mb-6"><p className="text-[10px] font-extrabold uppercase tracking-[.12em] text-[#1769aa]">Segurança</p><h1 className="mt-1 text-2xl font-bold text-slate-800">Auditoria</h1><p className="mt-1 text-sm text-slate-500">Registro imutável das ações administrativas relevantes.</p></header><form className="mb-5 grid gap-3 rounded-xl border border-slate-200 bg-white p-4 shadow-sm sm:grid-cols-[1fr_1fr_auto_auto]"><label className="grid gap-1 text-xs font-bold text-slate-600">Data inicial<input type="date" name="inicio" defaultValue={inicio} className="h-10 rounded-lg border border-slate-300 px-3 font-normal"/></label><label className="grid gap-1 text-xs font-bold text-slate-600">Data final<input type="date" name="fim" defaultValue={fim} className="h-10 rounded-lg border border-slate-300 px-3 font-normal"/></label><button className="self-end rounded-lg bg-[#1769aa] px-4 py-2.5 text-sm font-bold text-white">Filtrar</button><a href="/auditoria" className="self-end rounded-lg border border-slate-300 px-4 py-2.5 text-center text-sm font-bold text-slate-700">Limpar</a></form><section className="rounded-xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center gap-2 border-b border-slate-100 p-5"><ClipboardList size={18} className="text-[#1769aa]"/><strong className="text-sm text-slate-800">{rows.length} ação(ões)</strong></div><div className="divide-y divide-slate-100">{rows.map((row) => <article key={row.id} className="grid gap-1 p-4 sm:grid-cols-[190px_1.2fr_1fr_auto] sm:items-center"><p className="text-xs text-slate-500">{new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short" }).format(row.createdAt)}</p><p className="font-bold text-slate-800">{row.action}</p><p className="text-sm text-slate-600">{row.actor || "Sistema / visitante"} · {row.entityType}</p><p className="text-xs text-slate-500">{row.ipAddress || "Origem não informada"}</p></article>)}{!rows.length && <p className="p-8 text-center text-sm text-slate-500">Nenhuma ação no período informado.</p>}</div></section></main>;
}
