import Link from "next/link";
import { asc, eq } from "drizzle-orm";
import { Building2, Plus, UsersRound } from "lucide-react";
import { can } from "@/lib/auth/permissions";
import { requirePermission } from "@/lib/auth/authorization";
import { getDb } from "@/lib/db";
import { departments, members } from "@/lib/db/schema";

export default async function DepartmentsPage({ searchParams }: { searchParams: Promise<{ criado?: string }> }) {
  const current = await requirePermission("departamentos.visualizar"); const { criado } = await searchParams;
  const canManage = current.permissions.includes("*") || current.permissions.includes("departamentos.gerenciar") || can(current.roles, "departamentos.gerenciar");
  const rows = await getDb().select({ id: departments.id, name: departments.name, description: departments.description, active: departments.active, leader: members.fullName }).from(departments).leftJoin(members, eq(departments.leaderMemberId, members.id)).orderBy(asc(departments.name));
  return <main className="mx-auto max-w-5xl p-4 sm:p-7 lg:p-9"><div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p className="mb-1.5 text-[10px] font-extrabold uppercase tracking-[.12em] text-[#1769aa]">Organização</p><h1 className="text-2xl font-bold tracking-tight text-slate-800 sm:text-[28px]">Departamentos</h1><p className="mt-1.5 text-[13px] text-slate-500">Visualize os ministérios, integrantes e tarefas.</p></div>{canManage && <Link href="/departamentos/novo" className="inline-flex items-center gap-2 rounded-lg bg-[#1769aa] px-4 py-3 text-sm font-bold text-white"><Plus size={16}/>Novo departamento</Link>}</div>{criado && <div className="mb-5 rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800">Departamento criado com sucesso.</div>}<section className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><span className="text-sm font-bold text-slate-800">{rows.length} departamento(s)</span><Building2 size={18} className="text-slate-400"/></div>{rows.length === 0 ? <div className="grid min-h-64 place-items-center p-8 text-center"><div><UsersRound className="mx-auto text-slate-300" size={36}/><h2 className="mt-3 font-bold text-slate-800">Nenhum departamento cadastrado</h2><p className="mt-1 text-sm text-slate-500">Crie os ministérios e defina suas lideranças.</p></div></div> : <div className="divide-y divide-slate-100">{rows.map((department) => <article key={department.id} className="p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><Link href={`/departamentos/${department.id}`} className="text-base font-bold text-slate-800 hover:text-[#1769aa]">{department.name}</Link><p className="mt-1 text-sm text-slate-500">Liderança: {department.leader || "Não definida"}</p>{department.description && <p className="mt-3 max-w-2xl text-sm leading-6 text-slate-600">{department.description}</p>}</div><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold uppercase ${department.active ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-600"}`}>{department.active ? "Ativo" : "Inativo"}</span></div></article>)}</div>}</section></main>;
}
