import { desc, eq } from "drizzle-orm";
import { Radio, Plus } from "lucide-react";
import { createRadioStation } from "../mvp/actions";
import { can } from "@/lib/auth/permissions";
import { requirePermission } from "@/lib/auth/authorization";
import { getDb } from "@/lib/db";
import { radioStations } from "@/lib/db/schema";

export default async function RadioPage({ searchParams }: { searchParams: Promise<{ criado?: string; erro?: string }> }) {
  const current = await requirePermission("painel.visualizar"); const message = await searchParams; const stations = await getDb().select().from(radioStations).where(eq(radioStations.active, true)).orderBy(desc(radioStations.createdAt)); const manage = current.permissions.includes("*") || current.permissions.includes("conteudos.publicar") || can(current.roles, "conteudos.publicar");
  return <main className="mx-auto max-w-5xl p-4 sm:p-7 lg:p-9"><header className="mb-7"><p className="text-[10px] font-extrabold uppercase tracking-[.12em] text-[#1769aa]">Ao vivo</p><h1 className="mt-1 text-2xl font-bold text-slate-800">Rádio</h1><p className="mt-1 text-sm text-slate-500">Ouça a programação por URL de streaming.</p></header>{message.criado && <p className="mb-5 rounded-lg bg-emerald-50 p-3 text-sm text-emerald-800">Rádio adicionada.</p>}{message.erro && <p className="mb-5 rounded-lg bg-red-50 p-3 text-sm text-red-800">{message.erro}</p>}<div className="grid gap-5 lg:grid-cols-[1fr_350px]"><section className="space-y-4">{stations.length ? stations.map((station) => <article key={station.id} className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-lg bg-blue-50 text-[#1769aa]"><Radio size={19}/></span><div><h2 className="font-bold text-slate-800">{station.name}</h2><p className="text-xs text-slate-500">Transmissão ao vivo</p></div></div><audio controls preload="none" className="mt-5 w-full"><source src={station.streamUrl}/></audio><a className="mt-3 block break-all text-xs font-bold text-[#1769aa]" href={station.streamUrl} target="_blank" rel="noreferrer">Abrir streaming</a></article>) : <p className="rounded-xl border border-dashed border-slate-300 p-8 text-center text-sm text-slate-500">Nenhuma rádio configurada.</p>}</section>{manage && <aside className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="flex items-center gap-2 font-bold text-slate-800"><Plus size={17} className="text-[#1769aa]"/>Configurar rádio</h2><form action={createRadioStation} className="mt-5 space-y-3"><input name="name" required className="h-10 w-full rounded-lg border border-slate-300 px-3 text-sm" placeholder="Nome da rádio"/><input name="streamUrl" type="url" required className="h-10 w-full rounded-lg border border-slate-300 px-3 text-sm" placeholder="https://stream..."/><button className="w-full rounded-lg bg-[#1769aa] py-3 text-sm font-bold text-white">Salvar rádio</button></form></aside>}</div></main>;
}
