import { boolean, date, index, integer, jsonb, numeric, pgEnum, pgTable, primaryKey, text, timestamp, uniqueIndex, uuid, varchar } from "drizzle-orm/pg-core";

export const userStatus = pgEnum("user_status", ["active", "inactive", "invited"]);
export const memberStatus = pgEnum("member_status", ["visitor", "new_convert", "congregant", "active", "inactive", "transferred", "dismissed", "deceased", "follow_up"]);
export const financialAccountKind = pgEnum("financial_account_kind", ["cash", "bank"]);
export const financialMovementType = pgEnum("financial_movement_type", ["income", "expense"]);
export const agendaEventKind = pgEnum("agenda_event_kind", ["service", "event", "meeting"]);
export const agendaEventVisibility = pgEnum("agenda_event_visibility", ["public", "internal"]);

export const users = pgTable("users", {
  id: uuid("id").defaultRandom().primaryKey(),
  name: varchar("name", { length: 160 }).notNull(),
  username: varchar("username", { length: 80 }).notNull().unique(),
  email: varchar("email", { length: 255 }).notNull().unique(),
  passwordHash: text("password_hash").notNull(),
  sessionVersion: integer("session_version").default(1).notNull(),
  status: userStatus("status").default("active").notNull(),
  memberId: uuid("member_id").references(() => members.id, { onDelete: "set null" }).unique(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
});

export const roles = pgTable("roles", {
  id: uuid("id").defaultRandom().primaryKey(), name: varchar("name", { length: 100 }).notNull().unique(), slug: varchar("slug", { length: 100 }).notNull().unique(), description: text("description"), isSystem: boolean("is_system").default(true).notNull(),
});
export const permissions = pgTable("permissions", { id: uuid("id").defaultRandom().primaryKey(), code: varchar("code", { length: 120 }).notNull().unique(), description: text("description") });
export const userRoles = pgTable("user_roles", { userId: uuid("user_id").references(() => users.id, { onDelete: "cascade" }).notNull(), roleId: uuid("role_id").references(() => roles.id, { onDelete: "cascade" }).notNull() }, (t) => [primaryKey({ columns: [t.userId, t.roleId] })]);
export const rolePermissionAssignments = pgTable("role_permissions", { roleId: uuid("role_id").references(() => roles.id, { onDelete: "cascade" }).notNull(), permissionId: uuid("permission_id").references(() => permissions.id, { onDelete: "cascade" }).notNull() }, (t) => [primaryKey({ columns: [t.roleId, t.permissionId] })]);
export const userDepartmentScopes = pgTable("user_department_scopes", { userId: uuid("user_id").references(() => users.id, { onDelete: "cascade" }).notNull(), departmentId: uuid("department_id").references(() => departments.id, { onDelete: "cascade" }).notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (t) => [primaryKey({ columns: [t.userId, t.departmentId] })]);

export const auditLogs = pgTable("audit_logs", {
  id: uuid("id").defaultRandom().primaryKey(), actorId: uuid("actor_id").references(() => users.id, { onDelete: "set null" }), action: varchar("action", { length: 120 }).notNull(), entityType: varchar("entity_type", { length: 80 }).notNull(), entityId: uuid("entity_id"), metadata: jsonb("metadata").$type<Record<string, unknown>>().default({}).notNull(), previousData: jsonb("previous_data").$type<Record<string, unknown> | null>(), newData: jsonb("new_data").$type<Record<string, unknown> | null>(), ipAddress: varchar("ip_address", { length: 64 }), userAgent: varchar("user_agent", { length: 500 }), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
}, (t) => [index("audit_logs_created_at_idx").on(t.createdAt), index("audit_logs_entity_idx").on(t.entityType, t.entityId)]);
export const loginAttempts = pgTable("login_attempts", { id: uuid("id").defaultRandom().primaryKey(), identifierHash: varchar("identifier_hash", { length: 64 }).notNull(), successful: boolean("successful").notNull(), attemptedAt: timestamp("attempted_at", { withTimezone: true }).defaultNow().notNull() }, (t) => [index("login_attempts_identifier_time_idx").on(t.identifierHash, t.attemptedAt)]);
export const passwordResetTokens = pgTable("password_reset_tokens", { id: uuid("id").defaultRandom().primaryKey(), userId: uuid("user_id").references(() => users.id, { onDelete: "cascade" }).notNull(), tokenHash: varchar("token_hash", { length: 64 }).notNull().unique(), expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(), usedAt: timestamp("used_at", { withTimezone: true }), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (t) => [index("password_reset_tokens_user_idx").on(t.userId), index("password_reset_tokens_expiry_idx").on(t.expiresAt)]);

export const memberFamilies = pgTable("families", { id: uuid("id").defaultRandom().primaryKey(), name: varchar("name", { length: 160 }).notNull(), phone: varchar("phone", { length: 30 }), email: varchar("email", { length: 255 }), address: varchar("address", { length: 300 }), notesEncrypted: text("notes_encrypted"), active: boolean("active").default(true).notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull() }, (t) => [index("families_name_idx").on(t.name)]);
export const members = pgTable("members", {
  id: uuid("id").defaultRandom().primaryKey(), fullName: varchar("full_name", { length: 160 }).notNull(), preferredName: varchar("preferred_name", { length: 160 }), email: varchar("email", { length: 255 }), phone: varchar("phone", { length: 30 }), whatsapp: varchar("whatsapp", { length: 30 }), mobilePhone: varchar("mobile_phone", { length: 20 }), instagram: varchar("instagram", { length: 31 }), birthDate: date("birth_date"), maritalStatus: varchar("marital_status", { length: 40 }), occupation: varchar("occupation", { length: 120 }), city: varchar("city", { length: 100 }), state: varchar("state", { length: 2 }), address: varchar("address", { length: 300 }), neighborhood: varchar("neighborhood", { length: 120 }), zipCode: varchar("zip_code", { length: 12 }), documentNumber: varchar("document_number", { length: 30 }), cpfHash: varchar("cpf_hash", { length: 64 }), cpfEncrypted: text("cpf_encrypted"), photoUrl: text("photo_url"), guardianName: varchar("guardian_name", { length: 160 }), isMinor: boolean("is_minor").default(false).notNull(), familyId: uuid("family_id").references(() => memberFamilies.id, { onDelete: "set null" }), status: memberStatus("status").default("visitor").notNull(), registrationStatus: varchar("registration_status", { length: 20 }).default("approved").notNull(), conversionDate: date("conversion_date"), baptismDate: date("baptism_date"), entryDate: date("entry_date").defaultNow(), notes: text("notes"), notesEncrypted: text("notes_encrypted"), consentAt: timestamp("consent_at", { withTimezone: true }), archivedAt: timestamp("archived_at", { withTimezone: true }), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, (t) => [index("members_name_idx").on(t.fullName), index("members_status_idx").on(t.status), index("members_phone_idx").on(t.phone), index("members_family_idx").on(t.familyId)]);
export const familyMembers = pgTable("family_members", { familyId: uuid("family_id").references(() => memberFamilies.id, { onDelete: "cascade" }).notNull(), memberId: uuid("member_id").references(() => members.id, { onDelete: "cascade" }).notNull(), relationship: varchar("relationship", { length: 80 }), isPrimaryContact: boolean("is_primary_contact").default(false).notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (t) => [primaryKey({ columns: [t.familyId, t.memberId] })]);
export const memberHistory = pgTable("member_history", { id: uuid("id").defaultRandom().primaryKey(), memberId: uuid("member_id").references(() => members.id, { onDelete: "cascade" }).notNull(), action: varchar("action", { length: 120 }).notNull(), details: jsonb("details").$type<Record<string, unknown>>().default({}).notNull(), createdBy: uuid("created_by").references(() => users.id, { onDelete: "set null" }), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (t) => [index("member_history_member_idx").on(t.memberId, t.createdAt)]);
export const memberDocuments = pgTable("member_documents", { id: uuid("id").defaultRandom().primaryKey(), memberId: uuid("member_id").references(() => members.id, { onDelete: "cascade" }).notNull(), name: varchar("name", { length: 160 }).notNull(), url: text("url").notNull(), mimeType: varchar("mime_type", { length: 120 }), createdBy: uuid("created_by").references(() => users.id, { onDelete: "set null" }), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (t) => [index("member_documents_member_idx").on(t.memberId)]);

export const departments = pgTable("departments", { id: uuid("id").defaultRandom().primaryKey(), name: varchar("name", { length: 120 }).notNull().unique(), description: varchar("description", { length: 500 }), leaderMemberId: uuid("leader_member_id").references(() => members.id, { onDelete: "set null" }), active: boolean("active").default(true).notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (t) => [index("departments_leader_member_idx").on(t.leaderMemberId)]);
export const departmentMembers = pgTable("department_members", { departmentId: uuid("department_id").references(() => departments.id, { onDelete: "cascade" }).notNull(), memberId: uuid("member_id").references(() => members.id, { onDelete: "cascade" }).notNull(), role: varchar("role", { length: 100 }).default("integrante").notNull(), isLeader: boolean("is_leader").default(false).notNull(), joinedAt: date("joined_at").defaultNow(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (t) => [primaryKey({ columns: [t.departmentId, t.memberId] }), index("department_members_member_idx").on(t.memberId)]);
export const departmentTasks = pgTable("department_tasks", { id: uuid("id").defaultRandom().primaryKey(), departmentId: uuid("department_id").references(() => departments.id, { onDelete: "cascade" }).notNull(), title: varchar("title", { length: 180 }).notNull(), description: text("description"), dueAt: timestamp("due_at", { withTimezone: true }), assignedMemberId: uuid("assigned_member_id").references(() => members.id, { onDelete: "set null" }), status: varchar("status", { length: 30 }).default("open").notNull(), createdBy: uuid("created_by").references(() => users.id, { onDelete: "set null" }), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (t) => [index("department_tasks_department_idx").on(t.departmentId, t.status)]);

export const financialAccounts = pgTable("financial_accounts", { id: uuid("id").defaultRandom().primaryKey(), name: varchar("name", { length: 120 }).notNull().unique(), kind: financialAccountKind("kind").notNull(), active: boolean("active").default(true).notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() });
export const financialCategories = pgTable("financial_categories", { id: uuid("id").defaultRandom().primaryKey(), name: varchar("name", { length: 120 }).notNull(), type: financialMovementType("type").notNull(), active: boolean("active").default(true).notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (t) => [index("financial_categories_type_idx").on(t.type)]);
export const financialTransactions = pgTable("financial_transactions", { id: uuid("id").defaultRandom().primaryKey(), reference: varchar("reference", { length: 40 }).notNull().unique(), type: financialMovementType("type").notNull(), amount: numeric("amount", { precision: 14, scale: 2 }).notNull(), description: varchar("description", { length: 500 }).notNull(), accountId: uuid("account_id").references(() => financialAccounts.id, { onDelete: "restrict" }).notNull(), categoryId: uuid("category_id").references(() => financialCategories.id, { onDelete: "restrict" }).notNull(), createdBy: uuid("created_by").references(() => users.id, { onDelete: "restrict" }).notNull(), occurredAt: timestamp("occurred_at", { withTimezone: true }).defaultNow().notNull(), requiredApprovals: integer("required_approvals").default(1).notNull(), reversesTransactionId: uuid("reverses_transaction_id"), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (t) => [index("financial_transactions_occurred_at_idx").on(t.occurredAt), index("financial_transactions_account_idx").on(t.accountId)]);
export const financialTransactionApprovals = pgTable("financial_transaction_approvals", { transactionId: uuid("transaction_id").references(() => financialTransactions.id, { onDelete: "restrict" }).notNull(), approverId: uuid("approver_id").references(() => users.id, { onDelete: "restrict" }).notNull(), approvedAt: timestamp("approved_at", { withTimezone: true }).defaultNow().notNull() }, (t) => [primaryKey({ columns: [t.transactionId, t.approverId] }), index("financial_transaction_approvals_transaction_idx").on(t.transactionId)]);

export const agendaEvents = pgTable("agenda_events", { id: uuid("id").defaultRandom().primaryKey(), title: varchar("title", { length: 160 }).notNull(), kind: agendaEventKind("kind").notNull(), description: text("description"), startsAt: timestamp("starts_at", { withTimezone: true }).notNull(), endsAt: timestamp("ends_at", { withTimezone: true }), location: varchar("location", { length: 160 }), visibility: agendaEventVisibility("visibility").default("public").notNull(), capacity: integer("capacity"), registrationRequired: boolean("registration_required").default(false).notNull(), recurrenceRule: varchar("recurrence_rule", { length: 160 }), canceledAt: timestamp("canceled_at", { withTimezone: true }), createdBy: uuid("created_by").references(() => users.id, { onDelete: "restrict" }).notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (t) => [index("agenda_events_starts_at_idx").on(t.startsAt), index("agenda_events_visibility_idx").on(t.visibility)]);
export const eventRegistrations = pgTable("event_registrations", { id: uuid("id").defaultRandom().primaryKey(), eventId: uuid("event_id").references(() => agendaEvents.id, { onDelete: "cascade" }).notNull(), memberId: uuid("member_id").references(() => members.id, { onDelete: "set null" }), visitorName: varchar("visitor_name", { length: 160 }), visitorEmail: varchar("visitor_email", { length: 255 }), status: varchar("status", { length: 30 }).default("registered").notNull(), checkedInAt: timestamp("checked_in_at", { withTimezone: true }), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (t) => [index("event_registrations_event_idx").on(t.eventId, t.status), uniqueIndex("event_registrations_event_member_idx").on(t.eventId, t.memberId)]);
export const attendanceRecords = pgTable("attendance_records", { id: uuid("id").defaultRandom().primaryKey(), eventId: uuid("event_id").references(() => agendaEvents.id, { onDelete: "cascade" }).notNull(), memberId: uuid("member_id").references(() => members.id, { onDelete: "cascade" }).notNull(), present: boolean("present").default(true).notNull(), recordedBy: uuid("recorded_by").references(() => users.id, { onDelete: "set null" }), recordedAt: timestamp("recorded_at", { withTimezone: true }).defaultNow().notNull() }, (t) => [uniqueIndex("attendance_event_member_idx").on(t.eventId, t.memberId), index("attendance_event_idx").on(t.eventId)]);

export const serviceTeams = pgTable("service_teams", { id: uuid("id").defaultRandom().primaryKey(), name: varchar("name", { length: 120 }).notNull().unique(), departmentId: uuid("department_id").references(() => departments.id, { onDelete: "set null" }), active: boolean("active").default(true).notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() });
export const serviceAssignments = pgTable("service_assignments", { id: uuid("id").defaultRandom().primaryKey(), teamId: uuid("team_id").references(() => serviceTeams.id, { onDelete: "restrict" }).notNull(), eventId: uuid("event_id").references(() => agendaEvents.id, { onDelete: "set null" }), memberId: uuid("member_id").references(() => members.id, { onDelete: "restrict" }).notNull(), functionName: varchar("function_name", { length: 120 }), scheduledAt: timestamp("scheduled_at", { withTimezone: true }).notNull(), status: varchar("status", { length: 30 }).default("pending").notNull(), confirmedAt: timestamp("confirmed_at", { withTimezone: true }), replacementMemberId: uuid("replacement_member_id").references(() => members.id, { onDelete: "set null" }), notes: varchar("notes", { length: 500 }), createdBy: uuid("created_by").references(() => users.id, { onDelete: "restrict" }).notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (t) => [index("service_assignments_scheduled_at_idx").on(t.scheduledAt), index("service_assignments_team_idx").on(t.teamId), index("service_assignments_member_idx").on(t.memberId)]);

export const wallPosts = pgTable("wall_posts", { id: uuid("id").defaultRandom().primaryKey(), title: varchar("title", { length: 180 }).notNull(), body: text("body").notNull(), audience: varchar("audience", { length: 30 }).default("all").notNull(), departmentId: uuid("department_id").references(() => departments.id, { onDelete: "set null" }), publishedAt: timestamp("published_at", { withTimezone: true }).defaultNow().notNull(), expiresAt: timestamp("expires_at", { withTimezone: true }), createdBy: uuid("created_by").references(() => users.id, { onDelete: "set null" }), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (t) => [index("wall_posts_published_idx").on(t.publishedAt)]);
export const contentItems = pgTable("content_items", { id: uuid("id").defaultRandom().primaryKey(), type: varchar("type", { length: 30 }).notNull(), title: varchar("title", { length: 180 }).notNull(), description: text("description"), url: text("url").notNull(), speaker: varchar("speaker", { length: 160 }), publishedAt: timestamp("published_at", { withTimezone: true }).defaultNow().notNull(), visible: boolean("visible").default(true).notNull(), createdBy: uuid("created_by").references(() => users.id, { onDelete: "set null" }), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (t) => [index("content_items_type_published_idx").on(t.type, t.publishedAt)]);
export const radioStations = pgTable("radio_stations", { id: uuid("id").defaultRandom().primaryKey(), name: varchar("name", { length: 120 }).notNull(), streamUrl: text("stream_url").notNull(), active: boolean("active").default(true).notNull(), createdBy: uuid("created_by").references(() => users.id, { onDelete: "set null" }), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() });
export const prayerRequests = pgTable("prayer_requests", { id: uuid("id").defaultRandom().primaryKey(), requesterName: varchar("requester_name", { length: 160 }), requesterEmail: varchar("requester_email", { length: 255 }), bodyEncrypted: text("body_encrypted").notNull(), confidential: boolean("confidential").default(false).notNull(), status: varchar("status", { length: 30 }).default("open").notNull(), assignedTo: uuid("assigned_to").references(() => users.id, { onDelete: "set null" }), createdBy: uuid("created_by").references(() => users.id, { onDelete: "set null" }), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), answeredAt: timestamp("answered_at", { withTimezone: true }) }, (t) => [index("prayer_requests_status_idx").on(t.status, t.createdAt)]);
export const notifications = pgTable("notifications", { id: uuid("id").defaultRandom().primaryKey(), userId: uuid("user_id").references(() => users.id, { onDelete: "cascade" }).notNull(), title: varchar("title", { length: 160 }).notNull(), body: text("body"), href: varchar("href", { length: 500 }), readAt: timestamp("read_at", { withTimezone: true }), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (t) => [index("notifications_user_read_idx").on(t.userId, t.readAt, t.createdAt)]);
export const pushDevices = pgTable("push_devices", { id: uuid("id").defaultRandom().primaryKey(), userId: uuid("user_id").references(() => users.id, { onDelete: "cascade" }).notNull(), token: text("token").notNull().unique(), userAgent: varchar("user_agent", { length: 500 }), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull() }, (t) => [index("push_devices_user_idx").on(t.userId)]);
export const churchSettings = pgTable("church_settings", { id: uuid("id").defaultRandom().primaryKey(), churchName: varchar("church_name", { length: 160 }).notNull().default("Missão Resgatai"), slogan: varchar("slogan", { length: 240 }), address: varchar("address", { length: 300 }), phone: varchar("phone", { length: 30 }), email: varchar("email", { length: 255 }), instagramUrl: text("instagram_url"), youtubeUrl: text("youtube_url"), logoUrl: text("logo_url"), updatedBy: uuid("updated_by").references(() => users.id, { onDelete: "set null" }), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull() });
