import { desc } from "drizzle-orm";
import { HeartHandshake, LockKeyhole } from "lucide-react";
import { updatePrayerStatus } from "../mvp/actions";
import { requirePermission } from "@/lib/auth/authorization";
import { getDb } from "@/lib/db";
import { prayerRequests } from "@/lib/db/schema";
import { decryptSensitiveText } from "@/lib/security/encryption";

export default async function PrayersPage({ searchParams }: { searchParams: Promise<{ atualizado?: string; erro?: string }> }) {
  await requirePermission("oracao.gerenciar"); const message = await searchParams; const requests = await getDb().select().from(prayerRequests).orderBy(desc(prayerRequests.createdAt)).limit(100);
  return <main className="mx-auto max-w-5xl p-4 sm:p-7 lg:p-9"><header className="mb-7"><p className="text-[10px] font-extrabold uppercase tracking-[.12em] text-[#1769aa]">Cuidado pastoral</p><h1 className="mt-1 text-2xl font-bold text-slate-800">Pedidos de oração</h1><p className="mt-1 text-sm text-slate-500">Pedidos confidenciais são visíveis somente à equipe autorizada.</p></header>{message.atualizado && <p className="mb-5 rounded-lg bg-emerald-50 p-3 text-sm text-emerald-800">Pedido atualizado.</p>}{message.erro && <p className="mb-5 rounded-lg bg-red-50 p-3 text-sm text-red-800">{message.erro}</p>}<section className="space-y-4">{requests.length ? requests.map((request) => <article key={request.id} className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2"><h2 className="font-bold text-slate-800">{request.requesterName || "Pedido sem identificação"}</h2>{request.confidential && <span className="flex items-center gap-1 rounded-full bg-amber-50 px-2 py-1 text-[10px] font-bold text-amber-700"><LockKeyhole size={12}/>Confidencial</span>}</div>{request.requesterEmail && <p className="mt-1 text-xs text-slate-500">{request.requesterEmail}</p>}</div><form action={updatePrayerStatus} className="flex gap-2"><input type="hidden" name="id" value={request.id}/><select name="status" defaultValue={request.status} className="h-9 rounded-lg border border-slate-300 px-2 text-xs"><option value="open">Aberto</option><option value="praying">Em oração</option><option value="answered">Respondido</option><option value="archived">Arquivado</option></select><button className="rounded-lg border border-[#1769aa] px-3 text-xs font-bold text-[#1769aa]">Atualizar</button></form></div><p className="mt-4 whitespace-pre-wrap text-sm leading-6 text-slate-600">{decryptSensitiveText(request.bodyEncrypted)}</p><p className="mt-4 text-xs text-slate-500">{new Intl.DateTimeFormat("pt-BR", { timeZone: "America/Sao_Paulo", dateStyle: "medium", timeStyle: "short" }).format(request.createdAt)}</p></article>) : <p className="rounded-xl border border-dashed border-slate-300 p-8 text-center text-sm text-slate-500"><HeartHandshake className="mx-auto mb-3 text-slate-300"/>Nenhum pedido recebido.</p>}</section></main>;
}
