import Link from "next/link";
import { asc, eq } from "drizzle-orm";
import { ArrowLeft } from "lucide-react";
import { createDepartment } from "../actions";
import { getDb } from "@/lib/db";
import { members } from "@/lib/db/schema";

export default async function NewDepartmentPage({ searchParams }: { searchParams: Promise<{ erro?: string }> }) {
  const { erro } = await searchParams;
  const activeMembers = await getDb().select({ id: members.id, fullName: members.fullName }).from(members).where(eq(members.status, "active")).orderBy(asc(members.fullName));
  return <main className="mx-auto max-w-3xl p-4 sm:p-7 lg:p-9"><Link href="/departamentos" className="mb-5 inline-flex items-center gap-2 text-sm font-bold text-[#1769aa]"><ArrowLeft size={16}/>Voltar aos departamentos</Link><header className="mb-6"><p className="mb-1.5 text-[10px] font-extrabold uppercase tracking-[.12em] text-[#1769aa]">Organização</p><h1 className="text-2xl font-bold tracking-tight text-slate-800">Novo departamento</h1><p className="mt-1.5 text-[13px] text-slate-500">Cadastre um ministério e, se desejar, indique sua liderança.</p></header>{erro && <div className="mb-5 rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800">{erro}</div>}<form action={createDepartment} className="space-y-5"><section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="grid gap-4"><label className="grid gap-2 text-xs font-bold text-slate-700">Nome<input name="name" required maxLength={120} className="h-11 rounded-lg border border-slate-300 px-3 font-normal" placeholder="Ex.: Ministério de louvor"/></label><label className="grid gap-2 text-xs font-bold text-slate-700">Liderança (opcional)<span className="text-[11px] font-normal text-slate-500">Voce pode definir depois.</span><select name="leaderMemberId" className="h-11 rounded-lg border border-slate-300 px-3 font-normal"><option value="">Definir depois</option>{activeMembers.map((member) => <option key={member.id} value={member.id}>{member.fullName}</option>)}</select></label><label className="grid gap-2 text-xs font-bold text-slate-700">Descrição<textarea name="description" maxLength={500} rows={4} className="rounded-lg border border-slate-300 px-3 py-2 font-normal" placeholder="Finalidade e informações úteis do departamento"/></label></div></section><div className="flex justify-end gap-3"><Link href="/departamentos" className="rounded-lg border border-slate-300 px-4 py-3 text-sm font-bold text-slate-700">Cancelar</Link><button className="rounded-lg bg-[#1769aa] px-4 py-3 text-sm font-bold text-white">Criar departamento</button></div></form></main>;
}
