import { desc, eq, gt, isNull, or } from "drizzle-orm";
import { Megaphone, Plus } from "lucide-react";
import { createWallPost } from "../mvp/actions";
import { can } from "@/lib/auth/permissions";
import { requirePermission } from "@/lib/auth/authorization";
import { getDb } from "@/lib/db";
import { departments, wallPosts } from "@/lib/db/schema";

export default async function WallPage({ searchParams }: { searchParams: Promise<{ publicado?: string; erro?: string }> }) {
  const current = await requirePermission("painel.visualizar"); const message = await searchParams; const db = getDb(); const publish = current.permissions.includes("*") || current.permissions.includes("comunicacao.publicar") || can(current.roles, "comunicacao.publicar");
  const [posts, departmentRows] = await Promise.all([db.select({ id: wallPosts.id, title: wallPosts.title, body: wallPosts.body, audience: wallPosts.audience, publishedAt: wallPosts.publishedAt, department: departments.name }).from(wallPosts).leftJoin(departments, eq(wallPosts.departmentId, departments.id)).where(or(isNull(wallPosts.expiresAt), gt(wallPosts.expiresAt, new Date()))).orderBy(desc(wallPosts.publishedAt)).limit(100), db.select({ id: departments.id, name: departments.name }).from(departments).limit(100)]);
  return <main className="mx-auto max-w-6xl p-4 sm:p-7 lg:p-9"><header className="mb-7"><p className="text-[10px] font-extrabold uppercase tracking-[.12em] text-[#1769aa]">Comunicação</p><h1 className="mt-1 text-2xl font-bold text-slate-800">Mural de avisos</h1><p className="mt-1 text-sm text-slate-500">Comunicados gerais, segmentados ou de um ministério.</p></header>{message.publicado && <p className="mb-5 rounded-lg bg-emerald-50 p-3 text-sm text-emerald-800">Aviso publicado.</p>}{message.erro && <p className="mb-5 rounded-lg bg-red-50 p-3 text-sm text-red-800">{message.erro}</p>}<div className="grid gap-5 lg:grid-cols-[1fr_370px]"><section className="space-y-4">{posts.length ? posts.map((post) => <article key={post.id} className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-4"><div><h2 className="font-bold text-slate-800">{post.title}</h2><p className="mt-1 text-xs text-slate-500">{new Intl.DateTimeFormat("pt-BR", { dateStyle: "medium" }).format(post.publishedAt)} · {post.department || post.audience === "all" ? "Igreja toda" : post.audience}</p></div><Megaphone size={18} className="text-[#1769aa]"/></div><p className="mt-4 whitespace-pre-wrap text-sm leading-6 text-slate-600">{post.body}</p></article>) : <p className="rounded-xl border border-dashed border-slate-300 p-8 text-center text-sm text-slate-500">Nenhum aviso publicado.</p>}</section>{publish && <aside className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="flex items-center gap-2 font-bold text-slate-800"><Plus size={17} className="text-[#1769aa]"/>Publicar aviso</h2><form action={createWallPost} className="mt-5 space-y-3"><input name="title" required maxLength={180} className="h-10 w-full rounded-lg border border-slate-300 px-3 text-sm" placeholder="Título"/><textarea name="body" required rows={5} className="w-full rounded-lg border border-slate-300 p-3 text-sm" placeholder="Mensagem"/><select name="audience" className="h-10 w-full rounded-lg border border-slate-300 px-3 text-sm"><option value="all">Toda a igreja</option><option value="members">Membros</option><option value="leaders">Lideranças</option><option value="department">Departamento</option></select><select name="departmentId" className="h-10 w-full rounded-lg border border-slate-300 px-3 text-sm"><option value="">Sem departamento</option>{departmentRows.map((department) => <option key={department.id} value={department.id}>{department.name}</option>)}</select><label className="grid gap-1 text-xs font-bold text-slate-700">Expira em (opcional)<input name="expiresAt" type="datetime-local" className="h-10 rounded-lg border border-slate-300 px-3 font-normal"/></label><button className="w-full rounded-lg bg-[#1769aa] py-3 text-sm font-bold text-white">Publicar</button></form></aside>}</div></main>;
}
