import Link from "next/link";
import { notFound } from "next/navigation";
import { eq } from "drizzle-orm";
import { updateMember } from "../../actions";
import { requirePermission } from "@/lib/auth/authorization";
import { getDb } from "@/lib/db";
import { members } from "@/lib/db/schema";
import { MaskedInput } from "@/components/masked-input";

export default async function EditMemberPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ erro?: string }> }) {
  await requirePermission("membros.editar");
  const { id } = await params;
  const { erro } = await searchParams;
  const member = (await getDb().select().from(members).where(eq(members.id, id)).limit(1))[0];
  if (!member) notFound();
  return <main className="mx-auto max-w-4xl p-4 sm:p-7 lg:p-9"><Link href={`/membros/${id}`} className="text-sm font-bold text-[#7b4b2a]">← Voltar ao membro</Link><h1 className="mt-5 text-2xl font-bold text-slate-800">Editar membro</h1>{erro && <p className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-800">{erro}</p>}<form action={updateMember} className="mt-5 space-y-5"><input type="hidden" name="id" value={member.id}/><section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-1 text-xs font-bold text-slate-700 sm:col-span-2">Nome completo<input name="fullName" required defaultValue={member.fullName} className="h-10 rounded-lg border border-slate-300 px-3 font-normal"/></label><label className="grid gap-1 text-xs font-bold text-slate-700">E-mail<input name="email" type="email" defaultValue={member.email || ""} className="h-10 rounded-lg border border-slate-300 px-3 font-normal"/></label><label className="grid gap-1 text-xs font-bold text-slate-700">Celular / WhatsApp<MaskedInput name="mobilePhone" kind="phone" defaultValue={member.mobilePhone || member.whatsapp || ""}/></label><label className="grid gap-1 text-xs font-bold text-slate-700">CPF<MaskedInput name="cpf" kind="cpf" placeholder="000.000.000-00"/></label><label className="grid gap-1 text-xs font-bold text-slate-700">Nascimento<input name="birthDate" type="date" defaultValue={member.birthDate || ""} className="h-10 rounded-lg border border-slate-300 px-3 font-normal"/></label><label className="grid gap-1 text-xs font-bold text-slate-700">Cidade<input name="city" defaultValue={member.city || ""} className="h-10 rounded-lg border border-slate-300 px-3 font-normal"/></label><label className="grid gap-1 text-xs font-bold text-slate-700">UF<input name="state" maxLength={2} defaultValue={member.state || ""} className="h-10 rounded-lg border border-slate-300 px-3 font-normal"/></label><label className="grid gap-1 text-xs font-bold text-slate-700">Situação<select name="status" defaultValue={member.status} className="h-10 rounded-lg border border-slate-300 px-3 font-normal"><option value="visitor">Visitante</option><option value="new_convert">Novo convertido</option><option value="congregant">Congregado</option><option value="active">Membro ativo</option><option value="inactive">Afastado</option><option value="follow_up">Em acompanhamento</option></select></label><label className="grid gap-1 text-xs font-bold text-slate-700 sm:col-span-2">Observações<textarea name="notes" rows={4} defaultValue={member.notes || ""} className="rounded-lg border border-slate-300 p-3 font-normal"/></label></div></section><button className="rounded-lg bg-[#7b4b2a] px-5 py-3 text-sm font-bold text-white">Salvar alterações</button></form></main>;
}
