import { desc } from "drizzle-orm";
import { Plus, UsersRound } from "lucide-react";
import { createFamily } from "../mvp/actions";
import { requirePermission } from "@/lib/auth/authorization";
import { getDb } from "@/lib/db";
import { memberFamilies } from "@/lib/db/schema";

export default async function FamiliesPage({ searchParams }: { searchParams: Promise<{ criado?: string; erro?: string }> }) {
  await requirePermission("familias.gerenciar"); const message = await searchParams;
  const rows = await getDb().select().from(memberFamilies).orderBy(desc(memberFamilies.createdAt)).limit(100);
  return <main className="mx-auto max-w-6xl p-4 sm:p-7 lg:p-9"><header className="mb-7"><p className="text-[10px] font-extrabold uppercase tracking-[.12em] text-[#1769aa]">Cadastros</p><h1 className="mt-1 text-2xl font-bold text-slate-800">Famílias</h1><p className="mt-1 text-sm text-slate-500">Agrupe pessoas do mesmo núcleo familiar e mantenha o contato principal.</p></header>{message.criado && <p className="mb-5 rounded-lg bg-emerald-50 p-3 text-sm text-emerald-800">Família cadastrada.</p>}{message.erro && <p className="mb-5 rounded-lg bg-red-50 p-3 text-sm text-red-800">{message.erro}</p>}<div className="grid gap-5 lg:grid-cols-[1fr_360px]"><section className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 p-5"><strong className="text-sm text-slate-800">{rows.length} família(s)</strong><UsersRound size={18} className="text-slate-400"/></div><div className="divide-y divide-slate-100">{rows.length ? rows.map((family) => <article key={family.id} className="p-5"><h2 className="font-bold text-slate-800">{family.name}</h2><p className="mt-1 text-sm text-slate-500">{family.phone || family.email || "Sem contato informado"}</p><p className="mt-2 text-xs font-bold text-slate-500">{family.active ? "Ativa" : "Arquivada"}</p></article>) : <div className="grid min-h-48 place-items-center text-sm text-slate-500">Nenhuma família cadastrada.</div>}</div></section><aside className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="flex items-center gap-2 font-bold text-slate-800"><Plus size={17} className="text-[#1769aa]"/>Nova família</h2><form action={createFamily} className="mt-5 space-y-3"><label className="grid gap-1 text-xs font-bold text-slate-700">Nome da família<input name="name" required className="h-10 rounded-lg border border-slate-300 px-3 font-normal" placeholder="Família Silva"/></label><label className="grid gap-1 text-xs font-bold text-slate-700">Telefone<input name="phone" className="h-10 rounded-lg border border-slate-300 px-3 font-normal"/></label><label className="grid gap-1 text-xs font-bold text-slate-700">E-mail<input name="email" type="email" className="h-10 rounded-lg border border-slate-300 px-3 font-normal"/></label><label className="grid gap-1 text-xs font-bold text-slate-700">Endereço<input name="address" className="h-10 rounded-lg border border-slate-300 px-3 font-normal"/></label><label className="grid gap-1 text-xs font-bold text-slate-700">Observações<textarea name="notes" rows={3} className="rounded-lg border border-slate-300 p-3 font-normal"/></label><button className="w-full rounded-lg bg-[#1769aa] py-3 text-sm font-bold text-white">Salvar família</button></form></aside></div></main>;
}
