import ExcelJS from "exceljs";
import { and, asc, eq, gte, lte } from "drizzle-orm";
import { getCurrentAuthorization } from "@/lib/auth/authorization";
import { can } from "@/lib/auth/permissions";
import { getDb } from "@/lib/db";
import { brazilDateInputValue, endOfBrazilDay, startOfBrazilDay } from "@/lib/timezone";
import { agendaEvents, attendanceRecords, financialCategories, financialTransactions, members } from "@/lib/db/schema";

function dateRange(url: URL) { const fromText = url.searchParams.get("inicio"); const toText = url.searchParams.get("fim"); const from = fromText ? startOfBrazilDay(fromText) : undefined; const to = toText ? endOfBrazilDay(toText) : undefined; return { from: from && !Number.isNaN(from.getTime()) ? from : undefined, to: to && !Number.isNaN(to.getTime()) ? to : undefined }; }
function allowed(current: NonNullable<Awaited<ReturnType<typeof getCurrentAuthorization>>>, permission: string) { return current.permissions.includes("*") || current.permissions.includes(permission) || can(current.roles, permission); }
function setup(sheet: ExcelJS.Worksheet, columns: { header: string; key: string; width?: number }[]) { sheet.columns = columns; sheet.getRow(1).font = { bold: true }; sheet.views = [{ state: "frozen", ySplit: 1 }]; }

export async function GET(request: Request) {
  const current = await getCurrentAuthorization(); if (!current || !allowed(current, "relatorios.visualizar")) return new Response("Não autorizado", { status: 403 });
  const { from, to } = dateRange(new URL(request.url)); const db = getDb(); const memberFilters = [eq(members.registrationStatus, "approved")]; if (from) memberFilters.push(gte(members.createdAt, from)); if (to) memberFilters.push(lte(members.createdAt, to));
  const attendanceFilters = []; if (from) attendanceFilters.push(gte(attendanceRecords.recordedAt, from)); if (to) attendanceFilters.push(lte(attendanceRecords.recordedAt, to));
  const [memberRows, attendanceRows] = await Promise.all([db.select({ fullName: members.fullName, email: members.email, mobile: members.mobilePhone, status: members.status, createdAt: members.createdAt }).from(members).where(and(...memberFilters)).orderBy(asc(members.fullName)), db.select({ event: agendaEvents.title, member: members.fullName, present: attendanceRecords.present, recordedAt: attendanceRecords.recordedAt }).from(attendanceRecords).innerJoin(members, eq(attendanceRecords.memberId, members.id)).innerJoin(agendaEvents, eq(attendanceRecords.eventId, agendaEvents.id)).where(attendanceFilters.length ? and(...attendanceFilters) : undefined).orderBy(asc(attendanceRecords.recordedAt))]);
  const workbook = new ExcelJS.Workbook(); const memberSheet = workbook.addWorksheet("Membros"); setup(memberSheet, [{ header: "Nome", key: "fullName", width: 30 }, { header: "E-mail", key: "email", width: 30 }, { header: "Celular", key: "mobile", width: 18 }, { header: "Situação", key: "status", width: 18 }, { header: "Cadastro", key: "createdAt", width: 16 }]); memberRows.forEach((row) => memberSheet.addRow({ ...row, createdAt: row.createdAt.toLocaleDateString("pt-BR", { timeZone: "America/Sao_Paulo" }) }));
  const attendanceSheet = workbook.addWorksheet("Presenças"); setup(attendanceSheet, [{ header: "Evento", key: "event", width: 28 }, { header: "Membro", key: "member", width: 30 }, { header: "Situação", key: "present", width: 14 }, { header: "Registro", key: "recordedAt", width: 20 }]); attendanceRows.forEach((row) => attendanceSheet.addRow({ ...row, present: row.present ? "Presente" : "Falta", recordedAt: row.recordedAt.toLocaleString("pt-BR", { timeZone: "America/Sao_Paulo" }) }));
  if (allowed(current, "financeiro.visualizar")) { const financeFilters = []; if (from) financeFilters.push(gte(financialTransactions.occurredAt, from)); if (to) financeFilters.push(lte(financialTransactions.occurredAt, to)); const financeRows = await db.select({ reference: financialTransactions.reference, type: financialTransactions.type, amount: financialTransactions.amount, description: financialTransactions.description, occurredAt: financialTransactions.occurredAt, category: financialCategories.name }).from(financialTransactions).innerJoin(financialCategories, eq(financialTransactions.categoryId, financialCategories.id)).where(financeFilters.length ? and(...financeFilters) : undefined).orderBy(asc(financialTransactions.occurredAt)); const financeSheet = workbook.addWorksheet("Financeiro"); setup(financeSheet, [{ header: "Referência", key: "reference", width: 22 }, { header: "Tipo", key: "type", width: 12 }, { header: "Categoria", key: "category", width: 24 }, { header: "Descrição", key: "description", width: 40 }, { header: "Valor", key: "amount", width: 16 }, { header: "Data", key: "occurredAt", width: 18 }]); financeRows.forEach((row) => financeSheet.addRow({ ...row, type: row.type === "income" ? "Entrada" : "Saída", amount: Number(row.amount), occurredAt: row.occurredAt.toLocaleDateString("pt-BR", { timeZone: "America/Sao_Paulo" }) })); financeSheet.getColumn("amount").numFmt = 'R$ #,##0.00'; }
  const bytes = await workbook.xlsx.writeBuffer(); return new Response(bytes, { headers: { "Content-Type": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "Content-Disposition": `attachment; filename="relatorio-igreja-${brazilDateInputValue()}.xlsx"` } });
}
