"use client";

import { useState } from "react";

type User = { id: string; name: string; username: string; email: string; status: string; roles: string[]; memberId: string | null };
type Member = { id: string; fullName: string };
const roles = [["superadministrador", "Superadministrador"], ["pastor_presidente", "Pastor presidente"], ["pastor", "Pastor"], ["secretario", "Secretário"], ["tesoureiro", "Tesoureiro"], ["lider_departamento", "Líder de departamento"], ["auxiliar", "Auxiliar"], ["membro", "Membro"]] as const;

export function UserManager({ users, members, updateAction, statusAction }: { users: User[]; members: Member[]; updateAction: (formData: FormData) => void | Promise<void>; statusAction: (formData: FormData) => void | Promise<void> }) {
  const [selected, setSelected] = useState<User | null>(null);
  return <>
    <div className="grid gap-3">{users.map((user) => <article key={user.id} className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-bold text-slate-800">{user.name}</h2><p className="text-xs text-slate-500">{user.email} · @{user.username}</p><div className="mt-2 flex flex-wrap gap-1">{user.roles.map((role) => <span key={role} className="rounded-full bg-[#fff6c8] px-2 py-1 text-[10px] font-bold text-[#7b4b2a]">{role}</span>)}</div></div><div className="flex gap-2"><button onClick={() => setSelected(user)} className="rounded-lg border border-[#7b4b2a] px-3 py-2 text-xs font-bold text-[#7b4b2a]">Editar</button><form action={statusAction}><input type="hidden" name="userId" value={user.id}/><input type="hidden" name="status" value={user.status === "active" ? "inactive" : "active"}/><button onClick={(event) => { if (user.status === "active" && !window.confirm("Inativar esta conta? As sessões serão encerradas e o histórico preservado.")) event.preventDefault(); }} className="rounded-lg border border-slate-300 px-3 py-2 text-xs font-bold text-slate-700">{user.status === "active" ? "Inativar" : "Reativar"}</button></form></div></div></article>)}</div>
    {selected && <div className="fixed inset-0 z-50 grid place-items-center bg-black/45 p-4"><div className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white p-5 shadow-xl"><div className="flex items-center justify-between"><h2 className="text-lg font-bold text-slate-800">Editar usuário</h2><button onClick={() => setSelected(null)} className="text-sm font-bold text-slate-500">Fechar</button></div><form action={updateAction} className="mt-5 grid gap-4 sm:grid-cols-2"><input type="hidden" name="userId" value={selected.id}/><label className="grid gap-1 text-xs font-bold">Nome<input name="name" defaultValue={selected.name} className="h-10 rounded border border-slate-300 px-3 font-normal"/></label><label className="grid gap-1 text-xs font-bold">Usuário<input name="username" defaultValue={selected.username} className="h-10 rounded border border-slate-300 px-3 font-normal"/></label><label className="grid gap-1 text-xs font-bold sm:col-span-2">E-mail<input name="email" type="email" defaultValue={selected.email} className="h-10 rounded border border-slate-300 px-3 font-normal"/></label><label className="grid gap-1 text-xs font-bold sm:col-span-2">Membro vinculado<select name="memberId" defaultValue={selected.memberId || ""} className="h-10 rounded border border-slate-300 px-3 font-normal"><option value="">Não vincular agora</option>{members.map((member) => <option key={member.id} value={member.id}>{member.fullName}</option>)}</select></label><fieldset className="sm:col-span-2"><legend className="text-xs font-bold">Cargos</legend><div className="mt-2 grid gap-2 sm:grid-cols-2">{roles.map(([slug, label]) => <label key={slug} className="flex gap-2 rounded border border-slate-200 p-2 text-xs"><input type="checkbox" name="roleSlugs" value={slug} defaultChecked={selected.roles.includes(label) || selected.roles.includes(slug)}/>{label}</label>)}</div></fieldset><button className="sm:col-span-2 rounded-lg bg-[#7b4b2a] py-3 text-sm font-bold text-white">Salvar alterações</button></form></div></div>}
  </>;
}
