import Link from "next/link";
import { asc, desc } from "drizzle-orm";
import { assignUserDepartmentScope, setUserStatus } from "../actions";
import { requirePermission } from "@/lib/auth/authorization";
import { getDb } from "@/lib/db";
import { departments, users } from "@/lib/db/schema";

export default async function UserScopesPage({ searchParams }: { searchParams: Promise<{ escopoAtualizado?: string; statusAtualizado?: string; erro?: string }> }) {
  await requirePermission("usuarios.gerenciar"); const message = await searchParams; const db = getDb(); const [accounts, departmentRows] = await Promise.all([db.select({ id: users.id, name: users.name, email: users.email, status: users.status }).from(users).orderBy(desc(users.createdAt)), db.select({ id: departments.id, name: departments.name }).from(departments).orderBy(asc(departments.name))]);
  return <main className="mx-auto max-w-5xl p-4 sm:p-7 lg:p-9"><Link href="/usuarios" className="text-sm font-bold text-[#1769aa]">← Usuários</Link><h1 className="mt-5 text-2xl font-bold text-slate-800">Sessões e escopos de departamento</h1><p className="mt-1 text-sm text-slate-500">Ao inativar uma conta, todas as sessões dela são encerradas. Para líderes, cadastre somente os departamentos autorizados.</p>{message.escopoAtualizado && <p className="mt-5 rounded-lg bg-emerald-50 p-3 text-sm text-emerald-800">Escopo cadastrado.</p>}{message.statusAtualizado && <p className="mt-5 rounded-lg bg-emerald-50 p-3 text-sm text-emerald-800">Situação atualizada e sessões encerradas.</p>}{message.erro && <p className="mt-5 rounded-lg bg-red-50 p-3 text-sm text-red-800">{message.erro}</p>}<section className="mt-6 overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[780px] text-left text-sm"><thead className="bg-slate-50 text-[11px] uppercase text-slate-500"><tr><th className="px-5 py-3">Usuário</th><th className="px-5 py-3">Situação</th><th className="px-5 py-3">Departamento autorizado</th></tr></thead><tbody>{accounts.map((account) => <tr key={account.id} className="border-t border-slate-100"><td className="px-5 py-4"><p className="font-bold text-slate-800">{account.name}</p><p className="text-xs text-slate-500">{account.email}</p></td><td className="px-5 py-4"><form action={setUserStatus} className="flex gap-2"><input type="hidden" name="userId" value={account.id}/><select name="status" defaultValue={account.status} className="h-9 rounded-md border border-slate-300 px-2 text-xs"><option value="active">Ativo</option><option value="inactive">Inativo</option></select><button className="rounded-md border border-slate-300 px-2 text-xs font-bold text-slate-700">Salvar</button></form></td><td className="px-5 py-4"><form action={assignUserDepartmentScope} className="flex gap-2"><input type="hidden" name="userId" value={account.id}/><select name="departmentId" required className="h-9 rounded-md border border-slate-300 px-2 text-xs"><option value="">Selecionar</option>{departmentRows.map((department) => <option key={department.id} value={department.id}>{department.name}</option>)}</select><button className="rounded-md border border-[#1769aa] px-2 text-xs font-bold text-[#1769aa]">Autorizar</button></form></td></tr>)}</tbody></table></div></section></main>;
}
